const data = [
  {
    id: "AFG",
    name: "Afghanistan",
    flagImage:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/320px-Flag_of_the_Taliban.svg.png",
    flagEmoji: "🇦🇫",
    continent: "Asia",
    capital: "Kabul",
    subregion: "Southern Asia",
    area: 652230,
    population: 2837743,
  },
  {
    id: "ALB",
    name: "Albania",
    flagImage: "https://flagcdn.com/w320/al.png",
    flagEmoji: "🇦🇱",
    continent: "Europe",
    capital: "Tirana",
    subregion: "Southeast Europe",
    area: 28748,
    population: 2837743,
  },
  {
    id: "DZA",
    name: "Algeria",
    flagImage: "https://flagcdn.com/w320/dz.png",
    flagEmoji: "🇩🇿",
    continent: "Africa",
    capital: "Algiers",
    subregion: "Northern Africa",
    area: 2381741,
    population: 510713,
  },
  {
    id: "ASM",
    name: "American Samoa",
    flagImage: "https://flagcdn.com/w320/as.png",
    flagEmoji: "🇦🇸",
    continent: "Oceania",
    capital: "Pago Pago",
    subregion: "Polynesia",
    area: 199,
    population: 55197,
  },
  {
    id: "AND",
    name: "Andorra",
    flagImage: "https://flagcdn.com/w320/ad.png",
    flagEmoji: "🇦🇩",
    continent: "Europe",
    capital: "Andorra la Vella",
    subregion: "Southern Europe",
    area: 468,
    population: 77265,
  },
  {
    id: "AGO",
    name: "Angola",
    flagImage: "https://flagcdn.com/w320/ao.png",
    flagEmoji: "🇦🇴",
    continent: "Africa",
    capital: "Luanda",
    subregion: "Middle Africa",
    area: 1246700,
    population: 32866268,
  },
  {
    id: "AIA",
    name: "Anguilla",
    flagImage: "https://flagcdn.com/w320/ai.png",
    flagEmoji: "🇦🇮",
    continent: "North America",
    capital: "The Valley",
    subregion: "Caribbean",
    area: 91,
    population: 13452,
  },
  {
    id: "ATA",
    name: "Antarctica",
    flagImage: "https://flagcdn.com/w320/aq.png",
    flagEmoji: "🇦🇶",
    continent: "Antarctica",
    capital: "Desconocido",
    subregion: "Desconocido",
    area: 14000000,
    population: 1000,
  },
  {
    id: "ATG",
    name: "Antigua and Barbuda",
    flagImage: "https://flagcdn.com/w320/ag.png",
    flagEmoji: "🇦🇬",
    continent: "North America",
    capital: "Saint John's",
    subregion: "Caribbean",
    area: 442,
    population: 97928,
  },
  {
    id: "ARG",
    name: "Argentina",
    flagImage: "https://flagcdn.com/w320/ar.png",
    flagEmoji: "🇦🇷",
    continent: "South America",
    capital: "Buenos Aires",
    subregion: "South America",
    area: 2780400,
    population: 45376763,
  },
  {
    id: "ARM",
    name: "Armenia",
    flagImage: "https://flagcdn.com/w320/am.png",
    flagEmoji: "🇦🇲",
    continent: "Asia",
    capital: "Yerevan",
    subregion: "Western Asia",
    area: 29743,
    population: 2963234,
  },
  {
    id: "ABW",
    name: "Aruba",
    flagImage: "https://flagcdn.com/w320/aw.png",
    flagEmoji: "🇦🇼",
    continent: "North America",
    capital: "Oranjestad",
    subregion: "Caribbean",
    area: 180,
    population: 106766,
  },
  {
    id: "AUS",
    name: "Australia",
    flagImage: "https://flagcdn.com/w320/au.png",
    flagEmoji: "🇦🇺",
    continent: "Oceania",
    capital: "Canberra",
    subregion: "Australia and New Zealand",
    area: 7692024,
    population: 25687041,
  },
  {
    id: "AUT",
    name: "Austria",
    flagImage: "https://flagcdn.com/w320/at.png",
    flagEmoji: "🇦🇹",
    continent: "Europe",
    capital: "Vienna",
    subregion: "Central Europe",
    area: 83871,
    population: 8917205,
  },
  {
    id: "AZE",
    name: "Azerbaijan",
    flagImage: "https://flagcdn.com/w320/az.png",
    flagEmoji: "🇦🇿",
    continent: "Asia",
    capital: "Baku",
    subregion: "Western Asia",
    area: 86600,
    population: 10110116,
  },
  {
    id: "BHS",
    name: "Bahamas",
    flagImage: "https://flagcdn.com/w320/bs.png",
    flagEmoji: "🇧🇸",
    continent: "North America",
    capital: "Nassau",
    subregion: "Caribbean",
    area: 13943,
    population: 393248,
  },
  {
    id: "BHR",
    name: "Bahrain",
    flagImage: "https://flagcdn.com/w320/bh.png",
    flagEmoji: "🇧🇭",
    continent: "Asia",
    capital: "Manama",
    subregion: "Western Asia",
    area: 765,
    population: 1701583,
  },
  {
    id: "BGD",
    name: "Bangladesh",
    flagImage: "https://flagcdn.com/w320/bd.png",
    flagEmoji: "🇧🇩",
    continent: "Asia",
    capital: "Dhaka",
    subregion: "Southern Asia",
    area: 147570,
    population: 164689383,
  },
  {
    id: "BRB",
    name: "Barbados",
    flagImage: "https://flagcdn.com/w320/bb.png",
    flagEmoji: "🇧🇧",
    continent: "North America",
    capital: "Bridgetown",
    subregion: "Caribbean",
    area: 430,
    population: 287371,
  },
  {
    id: "BLR",
    name: "Belarus",
    flagImage: "https://flagcdn.com/w320/by.png",
    flagEmoji: "🇧🇾",
    continent: "Europe",
    capital: "Minsk",
    subregion: "Eastern Europe",
    area: 207600,
    population: 9398861,
  },
  {
    id: "BEL",
    name: "Belgium",
    flagImage: "https://flagcdn.com/w320/be.png",
    flagEmoji: "🇧🇪",
    continent: "Europe",
    capital: "Brussels",
    subregion: "Western Europe",
    area: 30528,
    population: 11555997,
  },
  {
    id: "BLZ",
    name: "Belize",
    flagImage: "https://flagcdn.com/w320/bz.png",
    flagEmoji: "🇧🇿",
    continent: "North America",
    capital: "Belmopan",
    subregion: "Central America",
    area: 22966,
    population: 397621,
  },
  {
    id: "BEN",
    name: "Benin",
    flagImage: "https://flagcdn.com/w320/bj.png",
    flagEmoji: "🇧🇯",
    continent: "Africa",
    capital: "Porto-Novo",
    subregion: "Western Africa",
    area: 112622,
    population: 12123198,
  },
  {
    id: "BMU",
    name: "Bermuda",
    flagImage: "https://flagcdn.com/w320/bm.png",
    flagEmoji: "🇧🇲",
    continent: "North America",
    capital: "Hamilton",
    subregion: "North America",
    area: 54,
    population: 63903,
  },
  {
    id: "BTN",
    name: "Bhutan",
    flagImage: "https://flagcdn.com/w320/bt.png",
    flagEmoji: "🇧🇹",
    continent: "Asia",
    capital: "Thimphu",
    subregion: "Southern Asia",
    area: 38394,
    population: 771612,
  },
  {
    id: "BOL",
    name: "Bolivia",
    flagImage: "https://flagcdn.com/w320/bo.png",
    flagEmoji: "🇧🇴",
    continent: "South America",
    capital: "Sucre",
    subregion: "South America",
    area: 1098581,
    population: 11673029,
  },
  {
    id: "BIH",
    name: "Bosnia and Herzegovina",
    flagImage: "https://flagcdn.com/w320/ba.png",
    flagEmoji: "🇧🇦",
    continent: "Europe",
    capital: "Sarajevo",
    subregion: "Southeast Europe",
    area: 51209,
    population: 3280815,
  },
  {
    id: "BWA",
    name: "Botswana",
    flagImage: "https://flagcdn.com/w320/bw.png",
    flagEmoji: "🇧🇼",
    continent: "Africa",
    capital: "Gaborone",
    subregion: "Southern Africa",
    area: 582000,
    population: 2351625,
  },
  {
    id: "BVT",
    name: "Bouvet Island",
    flagImage: "https://flagcdn.com/w320/bv.png",
    flagEmoji: "🇧🇻",
    continent: "Antarctica",
    capital: "Desconocido",
    subregion: "Desconocido",
    area: 49,
    population: 0,
  },
  {
    id: "BRA",
    name: "Brazil",
    flagImage: "https://flagcdn.com/w320/br.png",
    flagEmoji: "🇧🇷",
    continent: "South America",
    capital: "Brasília",
    subregion: "South America",
    area: 8515767,
    population: 212559409,
  },
  {
    id: "IOT",
    name: "British Indian Ocean Territory",
    flagImage: "https://flagcdn.com/w320/io.png",
    flagEmoji: "🇮🇴",
    continent: "Asia",
    capital: "Diego Garcia",
    subregion: "Eastern Africa",
    area: 60,
    population: 3000,
  },
  {
    id: "VGB",
    name: "British Virgin Islands",
    flagImage: "https://flagcdn.com/w320/vg.png",
    flagEmoji: "🇻🇬",
    continent: "North America",
    capital: "Road Town",
    subregion: "Caribbean",
    area: 151,
    population: 30237,
  },
  {
    id: "BRN",
    name: "Brunei",
    flagImage: "https://flagcdn.com/w320/bn.png",
    flagEmoji: "🇧🇳",
    continent: "Asia",
    capital: "Bandar Seri Begawan",
    subregion: "South-Eastern Asia",
    area: 5765,
    population: 437483,
  },
  {
    id: "BGR",
    name: "Bulgaria",
    flagImage: "https://flagcdn.com/w320/bg.png",
    flagEmoji: "🇧🇬",
    continent: "Europe",
    capital: "Sofia",
    subregion: "Southeast Europe",
    area: 110879,
    population: 6927288,
  },
  {
    id: "BFA",
    name: "Burkina Faso",
    flagImage: "https://flagcdn.com/w320/bf.png",
    flagEmoji: "🇧🇫",
    continent: "Africa",
    capital: "Ouagadougou",
    subregion: "Western Africa",
    area: 272967,
    population: 20903278,
  },
  {
    id: "BDI",
    name: "Burundi",
    flagImage: "https://flagcdn.com/w320/bi.png",
    flagEmoji: "🇧🇮",
    continent: "Africa",
    capital: "Gitega",
    subregion: "Eastern Africa",
    area: 27834,
    population: 11890781,
  },
  {
    id: "KHM",
    name: "Cambodia",
    flagImage: "https://flagcdn.com/w320/kh.png",
    flagEmoji: "🇰🇭",
    continent: "Asia",
    capital: "Phnom Penh",
    subregion: "South-Eastern Asia",
    area: 181035,
    population: 16718971,
  },
  {
    id: "CMR",
    name: "Cameroon",
    flagImage: "https://flagcdn.com/w320/cm.png",
    flagEmoji: "🇨🇲",
    continent: "Africa",
    capital: "Yaoundé",
    subregion: "Middle Africa",
    area: 475442,
    population: 26545864,
  },
  {
    id: "CAN",
    name: "Canada",
    flagImage: "https://flagcdn.com/w320/ca.png",
    flagEmoji: "🇨🇦",
    continent: "North America",
    capital: "Ottawa",
    subregion: "North America",
    area: 9984670,
    population: 38005238,
  },
  {
    id: "CPV",
    name: "Cape Verde",
    flagImage: "https://flagcdn.com/w320/cv.png",
    flagEmoji: "🇨🇻",
    continent: "Africa",
    capital: "Praia",
    subregion: "Western Africa",
    area: 4033,
    population: 555988,
  },
  {
    id: "BES",
    name: "Caribbean Netherlands",
    flagImage: "https://flagcdn.com/w320/bq.png",
    continent: "North America",
    capital: "Kralendijk",
    subregion: "Caribbean",
    area: 328,
    population: 25987,
  },
  {
    id: "CYM",
    name: "Cayman Islands",
    flagImage: "https://flagcdn.com/w320/ky.png",
    flagEmoji: "🇰🇾",
    continent: "North America",
    capital: "George Town",
    subregion: "Caribbean",
    area: 264,
    population: 65720,
  },
  {
    id: "CAF",
    name: "Central African Republic",
    flagImage: "https://flagcdn.com/w320/cf.png",
    flagEmoji: "🇨🇫",
    continent: "Africa",
    capital: "Bangui",
    subregion: "Middle Africa",
    area: 622984,
    population: 4829764,
  },
  {
    id: "TCD",
    name: "Chad",
    flagImage: "https://flagcdn.com/w320/td.png",
    flagEmoji: "🇹🇩",
    continent: "Africa",
    capital: "N'Djamena",
    subregion: "Middle Africa",
    area: 1284000,
    population: 16425859,
  },
  {
    id: "CHL",
    name: "Chile",
    flagImage: "https://flagcdn.com/w320/cl.png",
    flagEmoji: "🇨🇱",
    continent: "South America",
    capital: "Santiago",
    subregion: "South America",
    area: 756102,
    population: 19116209,
  },
  {
    id: "CHN",
    name: "China",
    flagImage: "https://flagcdn.com/w320/cn.png",
    flagEmoji: "🇨🇳",
    continent: "Asia",
    capital: "Beijing",
    subregion: "Eastern Asia",
    area: 9706961,
    population: 1402112000,
  },
  {
    id: "CXR",
    name: "Christmas Island",
    flagImage: "https://flagcdn.com/w320/cx.png",
    flagEmoji: "🇨🇽",
    continent: "Asia",
    capital: "Flying Fish Cove",
    subregion: "Australia and New Zealand",
    area: 135,
    population: 2072,
  },
  {
    id: "CCK",
    name: "Cocos (Keeling) Islands",
    flagImage: "https://flagcdn.com/w320/cc.png",
    flagEmoji: "🇨🇨",
    continent: "Asia",
    capital: "West Island",
    subregion: "Australia and New Zealand",
    area: 14,
    population: 544,
  },
  {
    id: "COL",
    name: "Colombia",
    flagImage: "https://flagcdn.com/w320/co.png",
    flagEmoji: "🇨🇴",
    continent: "South America",
    capital: "Bogotá",
    subregion: "South America",
    area: 1141748,
    population: 50882884,
  },
  {
    id: "COM",
    name: "Comoros",
    flagImage: "https://flagcdn.com/w320/km.png",
    flagEmoji: "🇰🇲",
    continent: "Africa",
    capital: "Moroni",
    subregion: "Eastern Africa",
    area: 1862,
    population: 869595,
  },
  {
    id: "COK",
    name: "Cook Islands",
    flagImage: "https://flagcdn.com/w320/ck.png",
    flagEmoji: "🇨🇰",
    continent: "Oceania",
    capital: "Avarua",
    subregion: "Polynesia",
    area: 236,
    population: 18100,
  },
  {
    id: "CRI",
    name: "Costa Rica",
    flagImage: "https://flagcdn.com/w320/cr.png",
    flagEmoji: "🇨🇷",
    continent: "North America",
    capital: "San José",
    subregion: "Central America",
    area: 51100,
    population: 5094114,
  },
  {
    id: "HRV",
    name: "Croatia",
    flagImage: "https://flagcdn.com/w320/hr.png",
    flagEmoji: "🇭🇷",
    continent: "Europe",
    capital: "Zagreb",
    subregion: "Southeast Europe",
    area: 56594,
    population: 4047200,
  },
  {
    id: "CUB",
    name: "Cuba",
    flagImage: "https://flagcdn.com/w320/cu.png",
    flagEmoji: "🇨🇺",
    continent: "North America",
    capital: "Havana",
    subregion: "Caribbean",
    area: 109884,
    population: 11326616,
  },
  {
    id: "CUW",
    name: "Curaçao",
    flagImage: "https://flagcdn.com/w320/cw.png",
    flagEmoji: "🇨🇼",
    continent: "North America",
    capital: "Willemstad",
    subregion: "Caribbean",
    area: 444,
    population: 155014,
  },
  {
    id: "CYP",
    name: "Cyprus",
    flagImage: "https://flagcdn.com/w320/cy.png",
    flagEmoji: "🇨🇾",
    continent: "Europe",
    capital: "Nicosia",
    subregion: "Southern Europe",
    area: 9251,
    population: 1207361,
  },
  {
    id: "CZE",
    name: "Czechia",
    flagImage: "https://flagcdn.com/w320/cz.png",
    flagEmoji: "🇨🇿",
    continent: "Europe",
    capital: "Prague",
    subregion: "Central Europe",
    area: 78865,
    population: 10698896,
  },
  {
    id: "COD",
    name: "DR Congo",
    flagImage: "https://flagcdn.com/w320/cd.png",
    flagEmoji: "🇨🇩",
    continent: "Africa",
    capital: "Kinshasa",
    subregion: "Middle Africa",
    area: 2344858,
    population: 89561404,
  },
  {
    id: "DNK",
    name: "Denmark",
    flagImage: "https://flagcdn.com/w320/dk.png",
    flagEmoji: "🇩🇰",
    continent: "Europe",
    capital: "Copenhagen",
    subregion: "Northern Europe",
    area: 43094,
    population: 5831404,
  },
  {
    id: "DJI",
    name: "Djibouti",
    flagImage: "https://flagcdn.com/w320/dj.png",
    flagEmoji: "🇩🇯",
    continent: "Africa",
    capital: "Djibouti",
    subregion: "Eastern Africa",
    area: 23200,
    population: 988002,
  },
  {
    id: "DMA",
    name: "Dominica",
    flagImage: "https://flagcdn.com/w320/dm.png",
    flagEmoji: "🇩🇲",
    continent: "North America",
    capital: "Roseau",
    subregion: "Caribbean",
    area: 751,
    population: 71991,
  },
  {
    id: "DOM",
    name: "Dominican Republic",
    flagImage: "https://flagcdn.com/w320/do.png",
    flagEmoji: "🇩🇴",
    continent: "North America",
    capital: "Santo Domingo",
    subregion: "Caribbean",
    area: 48671,
    population: 10847904,
  },
  {
    id: "ECU",
    name: "Ecuador",
    flagImage: "https://flagcdn.com/w320/ec.png",
    flagEmoji: "🇪🇨",
    continent: "South America",
    capital: "Quito",
    subregion: "South America",
    area: 276841,
    population: 17643060,
  },
  {
    id: "EGY",
    name: "Egypt",
    flagImage: "https://flagcdn.com/w320/eg.png",
    flagEmoji: "🇪🇬",
    continent: "Africa",
    capital: "Cairo",
    subregion: "Northern Africa",
    area: 1002450,
    population: 102334403,
  },
  {
    id: "SLV",
    name: "El Salvador",
    flagImage: "https://flagcdn.com/w320/sv.png",
    flagEmoji: "🇸🇻",
    continent: "North America",
    capital: "San Salvador",
    subregion: "Central America",
    area: 21041,
    population: 6486201,
  },
  {
    id: "GNQ",
    name: "Equatorial Guinea",
    flagImage: "https://flagcdn.com/w320/gq.png",
    flagEmoji: "🇬🇶",
    continent: "Africa",
    capital: "Malabo",
    subregion: "Middle Africa",
    area: 28051,
    population: 1402985,
  },
  {
    id: "ERI",
    name: "Eritrea",
    flagImage: "https://flagcdn.com/w320/er.png",
    flagEmoji: "🇪🇷",
    continent: "Africa",
    capital: "Asmara",
    subregion: "Eastern Africa",
    area: 117600,
    population: 5352000,
  },
  {
    id: "EST",
    name: "Estonia",
    flagImage: "https://flagcdn.com/w320/ee.png",
    flagEmoji: "🇪🇪",
    continent: "Europe",
    capital: "Tallinn",
    subregion: "Northern Europe",
    area: 45227,
    population: 1331057,
  },
  {
    id: "SWZ",
    name: "Eswatini",
    flagImage: "https://flagcdn.com/w320/sz.png",
    flagEmoji: "🇸🇿",
    continent: "Africa",
    capital: "Mbabane",
    subregion: "Southern Africa",
    area: 17364,
    population: 1160164,
  },
  {
    id: "ETH",
    name: "Ethiopia",
    flagImage: "https://flagcdn.com/w320/et.png",
    flagEmoji: "🇪🇹",
    continent: "Africa",
    capital: "Addis Ababa",
    subregion: "Eastern Africa",
    area: 1104300,
    population: 114963583,
  },
  {
    id: "FLK",
    name: "Falkland Islands",
    flagImage: "https://flagcdn.com/w320/fk.png",
    flagEmoji: "🇫🇰",
    continent: "South America",
    capital: "Stanley",
    subregion: "South America",
    area: 12173,
    population: 2563,
  },
  {
    id: "FRO",
    name: "Faroe Islands",
    flagImage: "https://flagcdn.com/w320/fo.png",
    flagEmoji: "🇫🇴",
    continent: "Europe",
    capital: "Tórshavn",
    subregion: "Northern Europe",
    area: 1393,
    population: 48865,
  },
  {
    id: "FJI",
    name: "Fiji",
    flagImage: "https://flagcdn.com/w320/fj.png",
    flagEmoji: "🇫🇯",
    continent: "Oceania",
    capital: "Suva",
    subregion: "Melanesia",
    area: 18272,
    population: 896444,
  },
  {
    id: "FIN",
    name: "Finland",
    flagImage: "https://flagcdn.com/w320/fi.png",
    flagEmoji: "🇫🇮",
    continent: "Europe",
    capital: "Helsinki",
    subregion: "Northern Europe",
    area: 338424,
    population: 5530719,
  },
  {
    id: "FRA",
    name: "France",
    flagImage: "https://flagcdn.com/w320/fr.png",
    flagEmoji: "🇫🇷",
    continent: "Europe",
    capital: "Paris",
    subregion: "Western Europe",
    area: 551695,
    population: 67391582,
  },
  {
    id: "GUF",
    name: "French Guiana",
    flagImage: "https://flagcdn.com/w320/gf.png",
    flagEmoji: "🇬🇫",
    continent: "South America",
    capital: "Cayenne",
    subregion: "South America",
    area: 83534,
    population: 254541,
  },
  {
    id: "PYF",
    name: "French Polynesia",
    flagImage: "https://flagcdn.com/w320/pf.png",
    flagEmoji: "🇵🇫",
    continent: "Oceania",
    capital: "Papeetē",
    subregion: "Polynesia",
    area: 4167,
    population: 280904,
  },
  {
    id: "ATF",
    name: "French Southern and Antarctic Lands",
    flagImage: "https://flagcdn.com/w320/tf.png",
    flagEmoji: "🇹🇫",
    continent: "Antarctica",
    capital: "Port-aux-Français",
    subregion: "Desconocido",
    area: 7747,
    population: 400,
  },
  {
    id: "GAB",
    name: "Gabon",
    flagImage: "https://flagcdn.com/w320/ga.png",
    flagEmoji: "🇬🇦",
    continent: "Africa",
    capital: "Libreville",
    subregion: "Middle Africa",
    area: 267668,
    population: 2225728,
  },
  {
    id: "GMB",
    name: "Gambia",
    flagImage: "https://flagcdn.com/w320/gm.png",
    flagEmoji: "🇬🇲",
    continent: "Africa",
    capital: "Banjul",
    subregion: "Western Africa",
    area: 10689,
    population: 2416664,
  },
  {
    id: "GEO",
    name: "Georgia",
    flagImage: "https://flagcdn.com/w320/ge.png",
    flagEmoji: "🇬🇪",
    continent: "Asia",
    capital: "Tbilisi",
    subregion: "Western Asia",
    area: 69700,
    population: 3714000,
  },
  {
    id: "DEU",
    name: "Germany",
    flagImage: "https://flagcdn.com/w320/de.png",
    flagEmoji: "🇩🇪",
    continent: "Europe",
    capital: "Berlin",
    subregion: "Western Europe",
    area: 357114,
    population: 83240525,
  },
  {
    id: "GHA",
    name: "Ghana",
    flagImage: "https://flagcdn.com/w320/gh.png",
    flagEmoji: "🇬🇭",
    continent: "Africa",
    capital: "Accra",
    subregion: "Western Africa",
    area: 238533,
    population: 31072945,
  },
  {
    id: "GIB",
    name: "Gibraltar",
    flagImage: "https://flagcdn.com/w320/gi.png",
    flagEmoji: "🇬🇮",
    continent: "Europe",
    capital: "Gibraltar",
    subregion: "Southern Europe",
    area: 6,
    population: 33691,
  },
  {
    id: "GRC",
    name: "Greece",
    flagImage: "https://flagcdn.com/w320/gr.png",
    flagEmoji: "🇬🇷",
    continent: "Europe",
    capital: "Athens",
    subregion: "Southern Europe",
    area: 131990,
    population: 10715549,
  },
  {
    id: "GRL",
    name: "Greenland",
    flagImage: "https://flagcdn.com/w320/gl.png",
    flagEmoji: "🇬🇱",
    continent: "North America",
    capital: "Nuuk",
    subregion: "North America",
    area: 2166086,
    population: 56367,
  },
  {
    id: "GRD",
    name: "Grenada",
    flagImage: "https://flagcdn.com/w320/gd.png",
    flagEmoji: "🇬🇩",
    continent: "North America",
    capital: "St. George's",
    subregion: "Caribbean",
    area: 344,
    population: 112519,
  },
  {
    id: "GLP",
    name: "Guadeloupe",
    flagImage: "https://flagcdn.com/w320/gp.png",
    flagEmoji: "🇬🇵",
    continent: "North America",
    capital: "Basse-Terre",
    subregion: "Caribbean",
    area: 1628,
    population: 400132,
  },
  {
    id: "GUM",
    name: "Guam",
    flagImage: "https://flagcdn.com/w320/gu.png",
    flagEmoji: "🇬🇺",
    continent: "Oceania",
    capital: "Hagåtña",
    subregion: "Micronesia",
    area: 549,
    population: 168783,
  },
  {
    id: "GTM",
    name: "Guatemala",
    flagImage: "https://flagcdn.com/w320/gt.png",
    flagEmoji: "🇬🇹",
    continent: "North America",
    capital: "Guatemala City",
    subregion: "Central America",
    area: 108889,
    population: 16858333,
  },
  {
    id: "GGY",
    name: "Guernsey",
    flagImage: "https://flagcdn.com/w320/gg.png",
    flagEmoji: "🇬🇬",
    continent: "Europe",
    capital: "St. Peter Port",
    subregion: "Northern Europe",
    area: 78,
    population: 62999,
  },
  {
    id: "GIN",
    name: "Guinea",
    flagImage: "https://flagcdn.com/w320/gn.png",
    flagEmoji: "🇬🇳",
    continent: "Africa",
    capital: "Conakry",
    subregion: "Western Africa",
    area: 245857,
    population: 13132792,
  },
  {
    id: "GNB",
    name: "Guinea-Bissau",
    flagImage: "https://flagcdn.com/w320/gw.png",
    flagEmoji: "🇬🇼",
    continent: "Africa",
    capital: "Bissau",
    subregion: "Western Africa",
    area: 36125,
    population: 1967998,
  },
  {
    id: "GUY",
    name: "Guyana",
    flagImage: "https://flagcdn.com/w320/gy.png",
    flagEmoji: "🇬🇾",
    continent: "South America",
    capital: "Georgetown",
    subregion: "South America",
    area: 214969,
    population: 786559,
  },
  {
    id: "HTI",
    name: "Haiti",
    flagImage: "https://flagcdn.com/w320/ht.png",
    flagEmoji: "🇭🇹",
    continent: "North America",
    capital: "Port-au-Prince",
    subregion: "Caribbean",
    area: 27750,
    population: 11402533,
  },
  {
    id: "HMD",
    name: "Heard Island and McDonald Islands",
    flagImage: "https://flagcdn.com/w320/hm.png",
    flagEmoji: "🇭🇲",
    continent: "Antarctica",
    capital: "Desconocido",
    subregion: "Desconocido",
    area: 412,
    population: 0,
  },
  {
    id: "HND",
    name: "Honduras",
    flagImage: "https://flagcdn.com/w320/hn.png",
    flagEmoji: "🇭🇳",
    continent: "North America",
    capital: "Tegucigalpa",
    subregion: "Central America",
    area: 112492,
    population: 9904608,
  },
  {
    id: "HKG",
    name: "Hong Kong",
    flagImage: "https://flagcdn.com/w320/hk.png",
    flagEmoji: "🇭🇰",
    continent: "Asia",
    capital: "City of Victoria",
    subregion: "Eastern Asia",
    area: 1104,
    population: 7500700,
  },
  {
    id: "HUN",
    name: "Hungary",
    flagImage: "https://flagcdn.com/w320/hu.png",
    flagEmoji: "🇭🇺",
    continent: "Europe",
    capital: "Budapest",
    subregion: "Central Europe",
    area: 93028,
    population: 9749763,
  },
  {
    id: "ISL",
    name: "Iceland",
    flagImage: "https://flagcdn.com/w320/is.png",
    flagEmoji: "🇮🇸",
    continent: "Europe",
    capital: "Reykjavik",
    subregion: "Northern Europe",
    area: 103000,
    population: 366425,
  },
  {
    id: "IND",
    name: "India",
    flagImage: "https://flagcdn.com/w320/in.png",
    flagEmoji: "🇮🇳",
    continent: "Asia",
    capital: "New Delhi",
    subregion: "Southern Asia",
    area: 3287590,
    population: 1380004385,
  },
  {
    id: "IDN",
    name: "Indonesia",
    flagImage: "https://flagcdn.com/w320/id.png",
    flagEmoji: "🇮🇩",
    continent: "Asia",
    capital: "Jakarta",
    subregion: "South-Eastern Asia",
    area: 1904569,
    population: 273523621,
  },
  {
    id: "IRN",
    name: "Iran",
    flagImage: "https://flagcdn.com/w320/ir.png",
    flagEmoji: "🇮🇷",
    continent: "Asia",
    capital: "Tehran",
    subregion: "Southern Asia",
    area: 1648195,
    population: 83992953,
  },
  {
    id: "IRQ",
    name: "Iraq",
    flagImage: "https://flagcdn.com/w320/iq.png",
    flagEmoji: "🇮🇶",
    continent: "Asia",
    capital: "Baghdad",
    subregion: "Western Asia",
    area: 438317,
    population: 40222503,
  },
  {
    id: "IRL",
    name: "Ireland",
    flagImage: "https://flagcdn.com/w320/ie.png",
    flagEmoji: "🇮🇪",
    continent: "Europe",
    capital: "Dublin",
    subregion: "Northern Europe",
    area: 70273,
    population: 4994724,
  },
  {
    id: "IMN",
    name: "Isle of Man",
    flagImage: "https://flagcdn.com/w320/im.png",
    flagEmoji: "🇮🇲",
    continent: "Europe",
    capital: "Douglas",
    subregion: "Northern Europe",
    area: 572,
    population: 85032,
  },
  {
    id: "ISR",
    name: "Israel",
    flagImage: "https://flagcdn.com/w320/il.png",
    flagEmoji: "🇮🇱",
    continent: "Asia",
    capital: "Jerusalem",
    subregion: "Western Asia",
    area: 20770,
    population: 9216900,
  },
  {
    id: "ITA",
    name: "Italy",
    flagImage: "https://flagcdn.com/w320/it.png",
    flagEmoji: "🇮🇹",
    continent: "Europe",
    capital: "Rome",
    subregion: "Southern Europe",
    area: 301336,
    population: 59554023,
  },
  {
    id: "CIV",
    name: "Ivory Coast",
    flagImage: "https://flagcdn.com/w320/ci.png",
    flagEmoji: "🇨🇮",
    continent: "Africa",
    capital: "Yamoussoukro",
    subregion: "Western Africa",
    area: 322463,
    population: 26378275,
  },
  {
    id: "JAM",
    name: "Jamaica",
    flagImage: "https://flagcdn.com/w320/jm.png",
    flagEmoji: "🇯🇲",
    continent: "North America",
    capital: "Kingston",
    subregion: "Caribbean",
    area: 10991,
    population: 2961161,
  },
  {
    id: "JPN",
    name: "Japan",
    flagImage: "https://flagcdn.com/w320/jp.png",
    flagEmoji: "🇯🇵",
    continent: "Asia",
    capital: "Tokyo",
    subregion: "Eastern Asia",
    area: 377930,
    population: 125836021,
  },
  {
    id: "JEY",
    name: "Jersey",
    flagImage: "https://flagcdn.com/w320/je.png",
    flagEmoji: "🇯🇪",
    continent: "Europe",
    capital: "Saint Helier",
    subregion: "Northern Europe",
    area: 116,
    population: 100800,
  },
  {
    id: "JOR",
    name: "Jordan",
    flagImage: "https://flagcdn.com/w320/jo.png",
    flagEmoji: "🇯🇴",
    continent: "Asia",
    capital: "Amman",
    subregion: "Western Asia",
    area: 89342,
    population: 10203140,
  },
  {
    id: "KAZ",
    name: "Kazakhstan",
    flagImage: "https://flagcdn.com/w320/kz.png",
    flagEmoji: "🇰🇿",
    continent: "Asia",
    capital: "Nur-Sultan",
    subregion: "Central Asia",
    area: 2724900,
    population: 18754440,
  },
  {
    id: "KEN",
    name: "Kenya",
    flagImage: "https://flagcdn.com/w320/ke.png",
    flagEmoji: "🇰🇪",
    continent: "Africa",
    capital: "Nairobi",
    subregion: "Eastern Africa",
    area: 580367,
    population: 53771300,
  },
  {
    id: "KIR",
    name: "Kiribati",
    flagImage: "https://flagcdn.com/w320/ki.png",
    flagEmoji: "🇰🇮",
    continent: "Oceania",
    capital: "South Tarawa",
    subregion: "Micronesia",
    area: 811,
    population: 119446,
  },
  {
    id: "UNK",
    name: "Kosovo",
    flagImage: "https://flagcdn.com/w320/xk.png",
    flagEmoji: "🇽🇰",
    continent: "Europe",
    capital: "Pristina",
    subregion: "Southeast Europe",
    area: 10908,
    population: 1775378,
  },
  {
    id: "KWT",
    name: "Kuwait",
    flagImage: "https://flagcdn.com/w320/kw.png",
    flagEmoji: "🇰🇼",
    continent: "Asia",
    capital: "Kuwait City",
    subregion: "Western Asia",
    area: 17818,
    population: 4270563,
  },
  {
    id: "KGZ",
    name: "Kyrgyzstan",
    flagImage: "https://flagcdn.com/w320/kg.png",
    flagEmoji: "🇰🇬",
    continent: "Asia",
    capital: "Bishkek",
    subregion: "Central Asia",
    area: 199951,
    population: 6591600,
  },
  {
    id: "LAO",
    name: "Laos",
    flagImage: "https://flagcdn.com/w320/la.png",
    flagEmoji: "🇱🇦",
    continent: "Asia",
    capital: "Vientiane",
    subregion: "South-Eastern Asia",
    area: 236800,
    population: 7275556,
  },
  {
    id: "LVA",
    name: "Latvia",
    flagImage: "https://flagcdn.com/w320/lv.png",
    flagEmoji: "🇱🇻",
    continent: "Europe",
    capital: "Riga",
    subregion: "Northern Europe",
    area: 64559,
    population: 1901548,
  },
  {
    id: "LBN",
    name: "Lebanon",
    flagImage: "https://flagcdn.com/w320/lb.png",
    flagEmoji: "🇱🇧",
    continent: "Asia",
    capital: "Beirut",
    subregion: "Western Asia",
    area: 10452,
    population: 6825442,
  },
  {
    id: "LSO",
    name: "Lesotho",
    flagImage: "https://flagcdn.com/w320/ls.png",
    flagEmoji: "🇱🇸",
    continent: "Africa",
    capital: "Maseru",
    subregion: "Southern Africa",
    area: 30355,
    population: 2142252,
  },
  {
    id: "LBR",
    name: "Liberia",
    flagImage: "https://flagcdn.com/w320/lr.png",
    flagEmoji: "🇱🇷",
    continent: "Africa",
    capital: "Monrovia",
    subregion: "Western Africa",
    area: 111369,
    population: 5057677,
  },
  {
    id: "LBY",
    name: "Libya",
    flagImage: "https://flagcdn.com/w320/ly.png",
    flagEmoji: "🇱🇾",
    continent: "Africa",
    capital: "Tripoli",
    subregion: "Northern Africa",
    area: 1759540,
    population: 6871287,
  },
  {
    id: "LIE",
    name: "Liechtenstein",
    flagImage: "https://flagcdn.com/w320/li.png",
    flagEmoji: "🇱🇮",
    continent: "Europe",
    capital: "Vaduz",
    subregion: "Western Europe",
    area: 160,
    population: 38137,
  },
  {
    id: "LTU",
    name: "Lithuania",
    flagImage: "https://flagcdn.com/w320/lt.png",
    flagEmoji: "🇱🇹",
    continent: "Europe",
    capital: "Vilnius",
    subregion: "Northern Europe",
    area: 65300,
    population: 2794700,
  },
  {
    id: "LUX",
    name: "Luxembourg",
    flagImage: "https://flagcdn.com/w320/lu.png",
    flagEmoji: "🇱🇺",
    continent: "Europe",
    capital: "Luxembourg",
    subregion: "Western Europe",
    area: 2586,
    population: 632275,
  },
  {
    id: "MAC",
    name: "Macau",
    flagImage: "https://flagcdn.com/w320/mo.png",
    flagEmoji: "🇲🇴",
    continent: "Asia",
    capital: "Desconocido",
    subregion: "Eastern Asia",
    area: 30,
    population: 649342,
  },
  {
    id: "MDG",
    name: "Madagascar",
    flagImage: "https://flagcdn.com/w320/mg.png",
    flagEmoji: "🇲🇬",
    continent: "Africa",
    capital: "Antananarivo",
    subregion: "Eastern Africa",
    area: 587041,
    population: 27691019,
  },
  {
    id: "MWI",
    name: "Malawi",
    flagImage: "https://flagcdn.com/w320/mw.png",
    flagEmoji: "🇲🇼",
    continent: "Africa",
    capital: "Lilongwe",
    subregion: "Eastern Africa",
    area: 118484,
    population: 19129955,
  },
  {
    id: "MYS",
    name: "Malaysia",
    flagImage: "https://flagcdn.com/w320/my.png",
    flagEmoji: "🇲🇾",
    continent: "Asia",
    capital: "Kuala Lumpur",
    subregion: "South-Eastern Asia",
    area: 330803,
    population: 32365998,
  },
  {
    id: "MDV",
    name: "Maldives",
    flagImage: "https://flagcdn.com/w320/mv.png",
    flagEmoji: "🇲🇻",
    continent: "Asia",
    capital: "Malé",
    subregion: "Southern Asia",
    area: 300,
    population: 540542,
  },
  {
    id: "MLI",
    name: "Mali",
    flagImage: "https://flagcdn.com/w320/ml.png",
    flagEmoji: "🇲🇱",
    continent: "Africa",
    capital: "Bamako",
    subregion: "Western Africa",
    area: 1240192,
    population: 20250834,
  },
  {
    id: "MLT",
    name: "Malta",
    flagImage: "https://flagcdn.com/w320/mt.png",
    flagEmoji: "🇲🇹",
    continent: "Europe",
    capital: "Valletta",
    subregion: "Southern Europe",
    area: 316,
    population: 525285,
  },
  {
    id: "MHL",
    name: "Marshall Islands",
    flagImage: "https://flagcdn.com/w320/mh.png",
    flagEmoji: "🇲🇭",
    continent: "Oceania",
    capital: "Majuro",
    subregion: "Micronesia",
    area: 181,
    population: 59194,
  },
  {
    id: "MTQ",
    name: "Martinique",
    flagImage: "https://flagcdn.com/w320/mq.png",
    flagEmoji: "🇲🇶",
    continent: "North America",
    capital: "Fort-de-France",
    subregion: "Caribbean",
    area: 1128,
    population: 378243,
  },
  {
    id: "MRT",
    name: "Mauritania",
    flagImage: "https://flagcdn.com/w320/mr.png",
    flagEmoji: "🇲🇷",
    continent: "Africa",
    capital: "Nouakchott",
    subregion: "Western Africa",
    area: 1030700,
    population: 4649660,
  },
  {
    id: "MUS",
    name: "Mauritius",
    flagImage: "https://flagcdn.com/w320/mu.png",
    flagEmoji: "🇲🇺",
    continent: "Africa",
    capital: "Port Louis",
    subregion: "Eastern Africa",
    area: 2040,
    population: 1265740,
  },
  {
    id: "MYT",
    name: "Mayotte",
    flagImage: "https://flagcdn.com/w320/yt.png",
    flagEmoji: "🇾🇹",
    continent: "Africa",
    capital: "Mamoudzou",
    subregion: "Eastern Africa",
    area: 374,
    population: 226915,
  },
  {
    id: "MEX",
    name: "Mexico",
    flagImage: "https://flagcdn.com/w320/mx.png",
    flagEmoji: "🇲🇽",
    continent: "North America",
    capital: "Mexico City",
    subregion: "North America",
    area: 1964375,
    population: 128932753,
  },
  {
    id: "FSM",
    name: "Micronesia",
    flagImage: "https://flagcdn.com/w320/fm.png",
    flagEmoji: "🇫🇲",
    continent: "Oceania",
    capital: "Palikir",
    subregion: "Micronesia",
    area: 702,
    population: 115021,
  },
  {
    id: "MDA",
    name: "Moldova",
    flagImage: "https://flagcdn.com/w320/md.png",
    flagEmoji: "🇲🇩",
    continent: "Europe",
    capital: "Chișinău",
    subregion: "Eastern Europe",
    area: 33846,
    population: 2617820,
  },
  {
    id: "MCO",
    name: "Monaco",
    flagImage: "https://flagcdn.com/w320/mc.png",
    flagEmoji: "🇲🇨",
    continent: "Europe",
    capital: "Monaco",
    subregion: "Western Europe",
    area: 2.02,
    population: 39244,
  },
  {
    id: "MNG",
    name: "Mongolia",
    flagImage: "https://flagcdn.com/w320/mn.png",
    flagEmoji: "🇲🇳",
    continent: "Asia",
    capital: "Ulan Bator",
    subregion: "Eastern Asia",
    area: 1564110,
    population: 3278292,
  },
  {
    id: "MNE",
    name: "Montenegro",
    flagImage: "https://flagcdn.com/w320/me.png",
    flagEmoji: "🇲🇪",
    continent: "Europe",
    capital: "Podgorica",
    subregion: "Southeast Europe",
    area: 13812,
    population: 621718,
  },
  {
    id: "MSR",
    name: "Montserrat",
    flagImage: "https://flagcdn.com/w320/ms.png",
    flagEmoji: "🇲🇸",
    continent: "North America",
    capital: "Plymouth",
    subregion: "Caribbean",
    area: 102,
    population: 4922,
  },
  {
    id: "MAR",
    name: "Morocco",
    flagImage: "https://flagcdn.com/w320/ma.png",
    flagEmoji: "🇲🇦",
    continent: "Africa",
    capital: "Rabat",
    subregion: "Northern Africa",
    area: 446550,
    population: 36910558,
  },
  {
    id: "MOZ",
    name: "Mozambique",
    flagImage: "https://flagcdn.com/w320/mz.png",
    flagEmoji: "🇲🇿",
    continent: "Africa",
    capital: "Maputo",
    subregion: "Eastern Africa",
    area: 801590,
    population: 31255435,
  },
  {
    id: "MMR",
    name: "Myanmar",
    flagImage: "https://flagcdn.com/w320/mm.png",
    flagEmoji: "🇲🇲",
    continent: "Asia",
    capital: "Naypyidaw",
    subregion: "South-Eastern Asia",
    area: 676578,
    population: 54409794,
  },
  {
    id: "NAM",
    name: "Namibia",
    flagImage: "https://flagcdn.com/w320/na.png",
    flagEmoji: "🇳🇦",
    continent: "Africa",
    capital: "Windhoek",
    subregion: "Southern Africa",
    area: 825615,
    population: 2540916,
  },
  {
    id: "NRU",
    name: "Nauru",
    flagImage: "https://flagcdn.com/w320/nr.png",
    flagEmoji: "🇳🇷",
    continent: "Oceania",
    capital: "Yaren",
    subregion: "Micronesia",
    area: 21,
    population: 10834,
  },
  {
    id: "NPL",
    name: "Nepal",
    flagImage: "https://flagcdn.com/w320/np.png",
    flagEmoji: "🇳🇵",
    continent: "Asia",
    capital: "Kathmandu",
    subregion: "Southern Asia",
    area: 147181,
    population: 29136808,
  },
  {
    id: "NLD",
    name: "Netherlands",
    flagImage: "https://flagcdn.com/w320/nl.png",
    flagEmoji: "🇳🇱",
    continent: "Europe",
    capital: "Amsterdam",
    subregion: "Western Europe",
    area: 41850,
    population: 16655799,
  },
  {
    id: "NCL",
    name: "New Caledonia",
    flagImage: "https://flagcdn.com/w320/nc.png",
    flagEmoji: "🇳🇨",
    continent: "Oceania",
    capital: "Nouméa",
    subregion: "Melanesia",
    area: 18575,
    population: 271960,
  },
  {
    id: "NZL",
    name: "New Zealand",
    flagImage: "https://flagcdn.com/w320/nz.png",
    flagEmoji: "🇳🇿",
    continent: "Oceania",
    capital: "Wellington",
    subregion: "Australia and New Zealand",
    area: 270467,
    population: 5084300,
  },
  {
    id: "NIC",
    name: "Nicaragua",
    flagImage: "https://flagcdn.com/w320/ni.png",
    flagEmoji: "🇳🇮",
    continent: "North America",
    capital: "Managua",
    subregion: "Central America",
    area: 130373,
    population: 6624554,
  },
  {
    id: "NER",
    name: "Niger",
    flagImage: "https://flagcdn.com/w320/ne.png",
    flagEmoji: "🇳🇪",
    continent: "Africa",
    capital: "Niamey",
    subregion: "Western Africa",
    area: 1267000,
    population: 24206636,
  },
  {
    id: "NGA",
    name: "Nigeria",
    flagImage: "https://flagcdn.com/w320/ng.png",
    flagEmoji: "🇳🇬",
    continent: "Africa",
    capital: "Abuja",
    subregion: "Western Africa",
    area: 923768,
    population: 206139587,
  },
  {
    id: "NIU",
    name: "Niue",
    flagImage: "https://flagcdn.com/w320/nu.png",
    flagEmoji: "🇳🇺",
    continent: "Oceania",
    capital: "Alofi",
    subregion: "Polynesia",
    area: 260,
    population: 1470,
  },
  {
    id: "NFK",
    name: "Norfolk Island",
    flagImage: "https://flagcdn.com/w320/nf.png",
    flagEmoji: "🇳🇫",
    continent: "Oceania",
    capital: "Kingston",
    subregion: "Australia and New Zealand",
    area: 36,
    population: 2302,
  },
  {
    id: "PRK",
    name: "North Korea",
    flagImage: "https://flagcdn.com/w320/kp.png",
    flagEmoji: "🇰🇵",
    continent: "Asia",
    capital: "Pyongyang",
    subregion: "Eastern Asia",
    area: 120538,
    population: 25778815,
  },
  {
    id: "MKD",
    name: "North Macedonia",
    flagImage: "https://flagcdn.com/w320/mk.png",
    flagEmoji: "🇲🇰",
    continent: "Europe",
    capital: "Skopje",
    subregion: "Southeast Europe",
    area: 25713,
    population: 2077132,
  },
  {
    id: "MNP",
    name: "Northern Mariana Islands",
    flagImage: "https://flagcdn.com/w320/mp.png",
    flagEmoji: "🇲🇵",
    continent: "Oceania",
    capital: "Saipan",
    subregion: "Micronesia",
    area: 464,
    population: 57557,
  },
  {
    id: "NOR",
    name: "Norway",
    flagImage: "https://flagcdn.com/w320/no.png",
    flagEmoji: "🇳🇴",
    continent: "Europe",
    capital: "Oslo",
    subregion: "Northern Europe",
    area: 323802,
    population: 5379475,
  },
  {
    id: "OMN",
    name: "Oman",
    flagImage: "https://flagcdn.com/w320/om.png",
    flagEmoji: "🇴🇲",
    continent: "Asia",
    capital: "Muscat",
    subregion: "Western Asia",
    area: 309500,
    population: 5106622,
  },
  {
    id: "PAK",
    name: "Pakistan",
    flagImage: "https://flagcdn.com/w320/pk.png",
    flagEmoji: "🇵🇰",
    continent: "Asia",
    capital: "Islamabad",
    subregion: "Southern Asia",
    area: 881912,
    population: 220892331,
  },
  {
    id: "PLW",
    name: "Palau",
    flagImage: "https://flagcdn.com/w320/pw.png",
    flagEmoji: "🇵🇼",
    continent: "Oceania",
    capital: "Ngerulmud",
    subregion: "Micronesia",
    area: 459,
    population: 18092,
  },
  {
    id: "PSE",
    name: "Palestine",
    flagImage: "https://flagcdn.com/w320/ps.png",
    flagEmoji: "🇵🇸",
    continent: "Asia",
    capital: "Ramallah",
    subregion: "Western Asia",
    area: 6220,
    population: 4803269,
  },
  {
    id: "PAN",
    name: "Panama",
    flagImage: "https://flagcdn.com/w320/pa.png",
    flagEmoji: "🇵🇦",
    continent: "North America",
    capital: "Panama City",
    subregion: "Central America",
    area: 75417,
    population: 4314768,
  },
  {
    id: "PNG",
    name: "Papua New Guinea",
    flagImage: "https://flagcdn.com/w320/pg.png",
    flagEmoji: "🇵🇬",
    continent: "Oceania",
    capital: "Port Moresby",
    subregion: "Melanesia",
    area: 462840,
    population: 8947027,
  },
  {
    id: "PRY",
    name: "Paraguay",
    flagImage: "https://flagcdn.com/w320/py.png",
    flagEmoji: "🇵🇾",
    continent: "South America",
    capital: "Asunción",
    subregion: "South America",
    area: 406752,
    population: 7132530,
  },
  {
    id: "PER",
    name: "Peru",
    flagImage: "https://flagcdn.com/w320/pe.png",
    flagEmoji: "🇵🇪",
    continent: "South America",
    capital: "Lima",
    subregion: "South America",
    area: 1285216,
    population: 32971846,
  },
  {
    id: "PHL",
    name: "Philippines",
    flagImage: "https://flagcdn.com/w320/ph.png",
    flagEmoji: "🇵🇭",
    continent: "Asia",
    capital: "Manila",
    subregion: "South-Eastern Asia",
    area: 342353,
    population: 109581085,
  },
  {
    id: "PCN",
    name: "Pitcairn Islands",
    flagImage: "https://flagcdn.com/w320/pn.png",
    flagEmoji: "🇵🇳",
    continent: "Oceania",
    capital: "Adamstown",
    subregion: "Polynesia",
    area: 47,
    population: 56,
  },
  {
    id: "POL",
    name: "Poland",
    flagImage: "https://flagcdn.com/w320/pl.png",
    flagEmoji: "🇵🇱",
    continent: "Europe",
    capital: "Warsaw",
    subregion: "Central Europe",
    area: 312679,
    population: 37950802,
  },
  {
    id: "PRT",
    name: "Portugal",
    flagImage: "https://flagcdn.com/w320/pt.png",
    flagEmoji: "🇵🇹",
    continent: "Europe",
    capital: "Lisbon",
    subregion: "Southern Europe",
    area: 92090,
    population: 10305564,
  },
  {
    id: "PRI",
    name: "Puerto Rico",
    flagImage: "https://flagcdn.com/w320/pr.png",
    flagEmoji: "🇵🇷",
    continent: "North America",
    capital: "San Juan",
    subregion: "Caribbean",
    area: 8870,
    population: 3194034,
  },
  {
    id: "QAT",
    name: "Qatar",
    flagImage: "https://flagcdn.com/w320/qa.png",
    flagEmoji: "🇶🇦",
    continent: "Asia",
    capital: "Doha",
    subregion: "Western Asia",
    area: 11586,
    population: 2881060,
  },
  {
    id: "COG",
    name: "Republic of the Congo",
    flagImage: "https://flagcdn.com/w320/cg.png",
    flagEmoji: "🇨🇬",
    continent: "Africa",
    capital: "Brazzaville",
    subregion: "Middle Africa",
    area: 342000,
    population: 89561404,
  },
  {
    id: "ROU",
    name: "Romania",
    flagImage: "https://flagcdn.com/w320/ro.png",
    flagEmoji: "🇷🇴",
    continent: "Europe",
    capital: "Bucharest",
    subregion: "Southeast Europe",
    area: 238391,
    population: 19286123,
  },
  {
    id: "RUS",
    name: "Russia",
    flagImage: "https://flagcdn.com/w320/ru.png",
    flagEmoji: "🇷🇺",
    continent: "Europe",
    capital: "Moscow",
    subregion: "Eastern Europe",
    area: 17098242,
    population: 144104080,
  },
  {
    id: "RWA",
    name: "Rwanda",
    flagImage: "https://flagcdn.com/w320/rw.png",
    flagEmoji: "🇷🇼",
    continent: "Africa",
    capital: "Kigali",
    subregion: "Eastern Africa",
    area: 26338,
    population: 12952209,
  },
  {
    id: "REU",
    name: "Réunion",
    flagImage: "https://flagcdn.com/w320/re.png",
    flagEmoji: "🇷🇪",
    continent: "Africa",
    capital: "Saint-Denis",
    subregion: "Eastern Africa",
    area: 2511,
    population: 840974,
  },
  {
    id: "BLM",
    name: "Saint Barthélemy",
    flagImage: "https://flagcdn.com/w320/bl.png",
    flagEmoji: "🇧🇱",
    continent: "North America",
    capital: "Gustavia",
    subregion: "Caribbean",
    area: 21,
    population: 4255,
  },
  {
    id: "SHN",
    name: "Saint Helena, Ascension and Tristan da Cunha",
    flagImage: "https://flagcdn.com/w320/sh.png",
    flagEmoji: "🇸🇭",
    continent: "Africa",
    capital: "Jamestown",
    subregion: "Western Africa",
    area: 394,
    population: 53192,
  },
  {
    id: "KNA",
    name: "Saint Kitts and Nevis",
    flagImage: "https://flagcdn.com/w320/kn.png",
    flagEmoji: "🇰🇳",
    continent: "North America",
    capital: "Basseterre",
    subregion: "Caribbean",
    area: 261,
    population: 53192,
  },
  {
    id: "LCA",
    name: "Saint Lucia",
    flagImage: "https://flagcdn.com/w320/lc.png",
    flagEmoji: "🇱🇨",
    continent: "North America",
    capital: "Castries",
    subregion: "Caribbean",
    area: 616,
    population: 183629,
  },
  {
    id: "MAF",
    name: "Saint Martin",
    flagImage: "https://flagcdn.com/w320/mf.png",
    flagEmoji: "🇲🇫",
    continent: "North America",
    capital: "Marigot",
    subregion: "Caribbean",
    area: 53,
    population: 38659,
  },
  {
    id: "SPM",
    name: "Saint Pierre and Miquelon",
    flagImage: "https://flagcdn.com/w320/pm.png",
    flagEmoji: "🇵🇲",
    continent: "North America",
    capital: "Saint-Pierre",
    subregion: "North America",
    area: 242,
    population: 6069,
  },
  {
    id: "VCT",
    name: "Saint Vincent and the Grenadines",
    flagImage: "https://flagcdn.com/w320/vc.png",
    flagEmoji: "🇻🇨",
    continent: "North America",
    capital: "Kingstown",
    subregion: "Caribbean",
    area: 389,
    population: 110947,
  },
  {
    id: "WSM",
    name: "Samoa",
    flagImage: "https://flagcdn.com/w320/ws.png",
    flagEmoji: "🇼🇸",
    continent: "Oceania",
    capital: "Apia",
    subregion: "Polynesia",
    area: 2842,
    population: 198410,
  },
  {
    id: "SMR",
    name: "San Marino",
    flagImage: "https://flagcdn.com/w320/sm.png",
    flagEmoji: "🇸🇲",
    continent: "Europe",
    capital: "City of San Marino",
    subregion: "Southern Europe",
    area: 61,
    population: 33938,
  },
  {
    id: "SAU",
    name: "Saudi Arabia",
    flagImage: "https://flagcdn.com/w320/sa.png",
    flagEmoji: "🇸🇦",
    continent: "Asia",
    capital: "Riyadh",
    subregion: "Western Asia",
    area: 2149690,
    population: 34813867,
  },
  {
    id: "SEN",
    name: "Senegal",
    flagImage: "https://flagcdn.com/w320/sn.png",
    flagEmoji: "🇸🇳",
    continent: "Africa",
    capital: "Dakar",
    subregion: "Western Africa",
    area: 196722,
    population: 16743930,
  },
  {
    id: "SRB",
    name: "Serbia",
    flagImage: "https://flagcdn.com/w320/rs.png",
    flagEmoji: "🇷🇸",
    continent: "Europe",
    capital: "Belgrade",
    subregion: "Southeast Europe",
    area: 88361,
    population: 6908224,
  },
  {
    id: "SYC",
    name: "Seychelles",
    flagImage: "https://flagcdn.com/w320/sc.png",
    flagEmoji: "🇸🇨",
    continent: "Africa",
    capital: "Victoria",
    subregion: "Eastern Africa",
    area: 452,
    population: 98462,
  },
  {
    id: "SLE",
    name: "Sierra Leone",
    flagImage: "https://flagcdn.com/w320/sl.png",
    flagEmoji: "🇸🇱",
    continent: "Africa",
    capital: "Freetown",
    subregion: "Western Africa",
    area: 71740,
    population: 7976985,
  },
  {
    id: "SGP",
    name: "Singapore",
    flagImage: "https://flagcdn.com/w320/sg.png",
    flagEmoji: "🇸🇬",
    continent: "Asia",
    capital: "Singapore",
    subregion: "South-Eastern Asia",
    area: 710,
    population: 5685807,
  },
  {
    id: "SXM",
    name: "Sint Maarten",
    flagImage: "https://flagcdn.com/w320/sx.png",
    flagEmoji: "🇸🇽",
    continent: "North America",
    capital: "Philipsburg",
    subregion: "Caribbean",
    area: 34,
    population: 40812,
  },
  {
    id: "SVK",
    name: "Slovakia",
    flagImage: "https://flagcdn.com/w320/sk.png",
    flagEmoji: "🇸🇰",
    continent: "Europe",
    capital: "Bratislava",
    subregion: "Central Europe",
    area: 49037,
    population: 5458827,
  },
  {
    id: "SVN",
    name: "Slovenia",
    flagImage: "https://flagcdn.com/w320/si.png",
    flagEmoji: "🇸🇮",
    continent: "Europe",
    capital: "Ljubljana",
    subregion: "Central Europe",
    area: 20273,
    population: 2100126,
  },
  {
    id: "SLB",
    name: "Solomon Islands",
    flagImage: "https://flagcdn.com/w320/sb.png",
    flagEmoji: "🇸🇧",
    continent: "Oceania",
    capital: "Honiara",
    subregion: "Melanesia",
    area: 28896,
    population: 686878,
  },
  {
    id: "SOM",
    name: "Somalia",
    flagImage: "https://flagcdn.com/w320/so.png",
    flagEmoji: "🇸🇴",
    continent: "Africa",
    capital: "Mogadishu",
    subregion: "Eastern Africa",
    area: 637657,
    population: 15893219,
  },
  {
    id: "ZAF",
    name: "South Africa",
    flagImage: "https://flagcdn.com/w320/za.png",
    flagEmoji: "🇿🇦",
    continent: "Africa",
    capital: "Pretoria",
    subregion: "Southern Africa",
    area: 1221037,
    population: 59308690,
  },
  {
    id: "SGS",
    name: "South Georgia",
    flagImage: "https://flagcdn.com/w320/gs.png",
    flagEmoji: "🇬🇸",
    continent: "Antarctica",
    capital: "King Edward Point",
    subregion: "Desconocido",
    area: 3903,
    population: 30,
  },
  {
    id: "KOR",
    name: "South Korea",
    flagImage: "https://flagcdn.com/w320/kr.png",
    flagEmoji: "🇰🇷",
    continent: "Asia",
    capital: "Seoul",
    subregion: "Eastern Asia",
    area: 100210,
    population: 51780579,
  },
  {
    id: "SSD",
    name: "South Sudan",
    flagImage: "https://flagcdn.com/w320/ss.png",
    flagEmoji: "🇸🇸",
    continent: "Africa",
    capital: "Juba",
    subregion: "Middle Africa",
    area: 619745,
    population: 11193729,
  },
  {
    id: "ESP",
    name: "Spain",
    flagImage: "https://flagcdn.com/w320/es.png",
    flagEmoji: "🇪🇸",
    continent: "Europe",
    capital: "Madrid",
    subregion: "Southern Europe",
    area: 505992,
    population: 47351567,
  },
  {
    id: "LKA",
    name: "Sri Lanka",
    flagImage: "https://flagcdn.com/w320/lk.png",
    flagEmoji: "🇱🇰",
    continent: "Asia",
    capital: "Sri Jayawardenepura Kotte",
    subregion: "Southern Asia",
    area: 65610,
    population: 21919000,
  },
  {
    id: "SDN",
    name: "Sudan",
    flagImage: "https://flagcdn.com/w320/sd.png",
    flagEmoji: "🇸🇩",
    continent: "Africa",
    capital: "Khartoum",
    subregion: "Northern Africa",
    area: 1886068,
    population: 43849269,
  },
  {
    id: "SUR",
    name: "Suriname",
    flagImage: "https://flagcdn.com/w320/sr.png",
    flagEmoji: "🇸🇷",
    continent: "South America",
    capital: "Paramaribo",
    subregion: "South America",
    area: 163820,
    population: 586634,
  },
  {
    id: "SJM",
    name: "Svalbard and Jan Mayen",
    flagImage: "https://flagcdn.com/w320/sj.png",
    flagEmoji: "🇸🇯",
    continent: "Europe",
    capital: "Longyearbyen",
    subregion: "Northern Europe",
    area: -1,
    population: 2562,
  },
  {
    id: "SWE",
    name: "Sweden",
    flagImage: "https://flagcdn.com/w320/se.png",
    flagEmoji: "🇸🇪",
    continent: "Europe",
    capital: "Stockholm",
    subregion: "Northern Europe",
    area: 450295,
    population: 10353442,
  },
  {
    id: "CHE",
    name: "Switzerland",
    flagImage: "https://flagcdn.com/w320/ch.png",
    flagEmoji: "🇨🇭",
    continent: "Europe",
    capital: "Bern",
    subregion: "Western Europe",
    area: 41284,
    population: 17500657,
  },
  {
    id: "SYR",
    name: "Syria",
    flagImage: "https://flagcdn.com/w320/sy.png",
    flagEmoji: "🇸🇾",
    continent: "Asia",
    capital: "Damascus",
    subregion: "Western Asia",
    area: 185180,
    population: 17500657,
  },
  {
    id: "STP",
    name: "São Tomé and Príncipe",
    flagImage: "https://flagcdn.com/w320/st.png",
    flagEmoji: "🇸🇹",
    continent: "Africa",
    capital: "São Tomé",
    subregion: "Middle Africa",
    area: 964,
    population: 219161,
  },
  {
    id: "TWN",
    name: "Taiwan",
    flagImage: "https://flagcdn.com/w320/tw.png",
    flagEmoji: "🇹🇼",
    continent: "Asia",
    capital: "Taipei",
    subregion: "Eastern Asia",
    area: 36193,
    population: 23503349,
  },
  {
    id: "TJK",
    name: "Tajikistan",
    flagImage: "https://flagcdn.com/w320/tj.png",
    flagEmoji: "🇹🇯",
    continent: "Asia",
    capital: "Dushanbe",
    subregion: "Central Asia",
    area: 143100,
    population: 9537642,
  },
  {
    id: "TZA",
    name: "Tanzania",
    flagImage: "https://flagcdn.com/w320/tz.png",
    flagEmoji: "🇹🇿",
    continent: "Africa",
    capital: "Dodoma",
    subregion: "Eastern Africa",
    area: 945087,
    population: 59734213,
  },
  {
    id: "THA",
    name: "Thailand",
    flagImage: "https://flagcdn.com/w320/th.png",
    flagEmoji: "🇹🇭",
    continent: "Asia",
    capital: "Bangkok",
    subregion: "South-Eastern Asia",
    area: 513120,
    population: 69799978,
  },
  {
    id: "TLS",
    name: "Timor-Leste",
    flagImage: "https://flagcdn.com/w320/tl.png",
    flagEmoji: "🇹🇱",
    continent: "Oceania",
    capital: "Dili",
    subregion: "South-Eastern Asia",
    area: 14874,
    population: 1318442,
  },
  {
    id: "TGO",
    name: "Togo",
    flagImage: "https://flagcdn.com/w320/tg.png",
    flagEmoji: "🇹🇬",
    continent: "Africa",
    capital: "Lomé",
    subregion: "Western Africa",
    area: 56785,
    population: 8278737,
  },
  {
    id: "TKL",
    name: "Tokelau",
    flagImage: "https://flagcdn.com/w320/tk.png",
    flagEmoji: "🇹🇰",
    continent: "Oceania",
    capital: "Fakaofo",
    subregion: "Polynesia",
    area: 12,
    population: 1411,
  },
  {
    id: "TON",
    name: "Tonga",
    flagImage: "https://flagcdn.com/w320/to.png",
    flagEmoji: "🇹🇴",
    continent: "Oceania",
    capital: "Nuku'alofa",
    subregion: "Polynesia",
    area: 747,
    population: 105697,
  },
  {
    id: "TTO",
    name: "Trinidad and Tobago",
    flagImage: "https://flagcdn.com/w320/tt.png",
    flagEmoji: "🇹🇹",
    continent: "North America",
    capital: "Port of Spain",
    subregion: "Caribbean",
    area: 5130,
    population: 1399491,
  },
  {
    id: "TUN",
    name: "Tunisia",
    flagImage: "https://flagcdn.com/w320/tn.png",
    flagEmoji: "🇹🇳",
    continent: "Africa",
    capital: "Tunis",
    subregion: "Northern Africa",
    area: 163610,
    population: 11818618,
  },
  {
    id: "TUR",
    name: "Turkey",
    flagImage: "https://flagcdn.com/w320/tr.png",
    flagEmoji: "🇹🇷",
    continent: "Asia",
    capital: "Ankara",
    subregion: "Western Asia",
    area: 783562,
    population: 84339067,
  },
  {
    id: "TKM",
    name: "Turkmenistan",
    flagImage: "https://flagcdn.com/w320/tm.png",
    flagEmoji: "🇹🇲",
    continent: "Asia",
    capital: "Ashgabat",
    subregion: "Central Asia",
    area: 488100,
    population: 6031187,
  },
  {
    id: "TCA",
    name: "Turks and Caicos Islands",
    flagImage: "https://flagcdn.com/w320/tc.png",
    flagEmoji: "🇹🇨",
    continent: "North America",
    capital: "Cockburn Town",
    subregion: "Caribbean",
    area: 948,
    population: 38718,
  },
  {
    id: "TUV",
    name: "Tuvalu",
    flagImage: "https://flagcdn.com/w320/tv.png",
    flagEmoji: "🇹🇻",
    continent: "Oceania",
    capital: "Funafuti",
    subregion: "Polynesia",
    area: 26,
    population: 11792,
  },
  {
    id: "UGA",
    name: "Uganda",
    flagImage: "https://flagcdn.com/w320/ug.png",
    flagEmoji: "🇺🇬",
    continent: "Africa",
    capital: "Kampala",
    subregion: "Eastern Africa",
    area: 241550,
    population: 45741000,
  },
  {
    id: "UKR",
    name: "Ukraine",
    flagImage: "https://flagcdn.com/w320/ua.png",
    flagEmoji: "🇺🇦",
    continent: "Europe",
    capital: "Kyiv",
    subregion: "Eastern Europe",
    area: 603500,
    population: 44134693,
  },
  {
    id: "ARE",
    name: "United Arab Emirates",
    flagImage: "https://flagcdn.com/w320/ae.png",
    flagEmoji: "🇦🇪",
    continent: "Asia",
    capital: "Abu Dhabi",
    subregion: "Western Asia",
    area: 83600,
    population: 9890400,
  },
  {
    id: "GBR",
    name: "United Kingdom",
    flagImage: "https://flagcdn.com/w320/gb.png",
    flagEmoji: "🇬🇧",
    continent: "Europe",
    capital: "London",
    subregion: "Northern Europe",
    area: 242900,
    population: 67215293,
  },
  {
    id: "USA",
    name: "United States",
    flagImage: "https://flagcdn.com/w320/us.png",
    flagEmoji: "🇺🇸",
    continent: "North America",
    capital: "Washington, D.C.",
    subregion: "North America",
    area: 9372610,
    population: 329484123,
  },
  {
    id: "UMI",
    name: "United States Minor Outlying Islands",
    flagImage: "https://flagcdn.com/w320/um.png",
    flagEmoji: "🇺🇲",
    continent: "Oceania",
    capital: "Desconocido",
    subregion: "North America",
    area: 34.2,
    population: 300,
  },
  {
    id: "VIR",
    name: "United States Virgin Islands",
    flagImage: "https://flagcdn.com/w320/vi.png",
    flagEmoji: "🇻🇮",
    continent: "North America",
    capital: "Charlotte Amalie",
    subregion: "Caribbean",
    area: 347,
    population: 106290,
  },
  {
    id: "URY",
    name: "Uruguay",
    flagImage: "https://flagcdn.com/w320/uy.png",
    flagEmoji: "🇺🇾",
    continent: "South America",
    capital: "Montevideo",
    subregion: "South America",
    area: 181034,
    population: 3473727,
  },
  {
    id: "UZB",
    name: "Uzbekistan",
    flagImage: "https://flagcdn.com/w320/uz.png",
    flagEmoji: "🇺🇿",
    continent: "Asia",
    capital: "Tashkent",
    subregion: "Central Asia",
    area: 447400,
    population: 34232050,
  },
  {
    id: "VUT",
    name: "Vanuatu",
    flagImage: "https://flagcdn.com/w320/vu.png",
    flagEmoji: "🇻🇺",
    continent: "Oceania",
    capital: "Port Vila",
    subregion: "Melanesia",
    area: 12189,
    population: 307150,
  },
  {
    id: "VAT",
    name: "Vatican City",
    flagImage: "https://flagcdn.com/w320/va.png",
    flagEmoji: "🇻🇦",
    continent: "Europe",
    capital: "Vatican City",
    subregion: "Southern Europe",
    area: 0.44,
    population: 451,
  },
  {
    id: "VEN",
    name: "Venezuela",
    flagImage: "https://flagcdn.com/w320/ve.png",
    flagEmoji: "🇻🇪",
    continent: "South America",
    capital: "Caracas",
    subregion: "South America",
    area: 916445,
    population: 28435943,
  },
  {
    id: "VNM",
    name: "Vietnam",
    flagImage: "https://flagcdn.com/w320/vn.png",
    flagEmoji: "🇻🇳",
    continent: "Asia",
    capital: "Hanoi",
    subregion: "South-Eastern Asia",
    area: 331212,
    population: 97338583,
  },
  {
    id: "WLF",
    name: "Wallis and Futuna",
    flagImage: "https://flagcdn.com/w320/wf.png",
    flagEmoji: "🇼🇫",
    continent: "Oceania",
    capital: "Mata-Utu",
    subregion: "Polynesia",
    area: 142,
    population: 11750,
  },
  {
    id: "ESH",
    name: "Western Sahara",
    flagImage: "https://flagcdn.com/w320/eh.png",
    flagEmoji: "🇪🇭",
    continent: "Africa",
    capital: "El Aaiún",
    subregion: "Northern Africa",
    area: 266000,
    population: 510713,
  },
  {
    id: "YEM",
    name: "Yemen",
    flagImage: "https://flagcdn.com/w320/ye.png",
    flagEmoji: "🇾🇪",
    continent: "Asia",
    capital: "Sana'a",
    subregion: "Western Asia",
    area: 527968,
    population: 29825968,
  },
  {
    id: "ZMB",
    name: "Zambia",
    flagImage: "https://flagcdn.com/w320/zm.png",
    flagEmoji: "🇿🇲",
    continent: "Africa",
    capital: "Lusaka",
    subregion: "Eastern Africa",
    area: 752612,
    population: 18383956,
  },
  {
    id: "ZWE",
    name: "Zimbabwe",
    flagImage: "https://flagcdn.com/w320/zw.png",
    flagEmoji: "🇿🇼",
    continent: "Africa",
    capital: "Harare",
    subregion: "Eastern Africa",
    area: 390757,
    population: 14862927,
  },
  {
    id: "ALA",
    name: "Åland Islands",
    flagImage: "https://flagcdn.com/w320/ax.png",
    flagEmoji: "🇦🇽",
    continent: "Europe",
    capital: "Mariehamn",
    subregion: "Northern Europe",
    area: 1580,
    population: 29458,
  },
];

module.exports = data;